version: '3'

services:
    web:
        image: tiangolo/uwsgi-nginx-flask:python3.8
        volumes:
            - .:/app
        ports:
            - "80:80"
        environment:
            - FLASK_APP=main.py
            - FLASK_DEBUG=1
            - STATIC_INDEX=1
            - 'RUN=flask run --host=0.0.0.0 --port=80'
        command: bash -c  "/usr/local/bin/pip install unidecode && flask run --host=0.0.0.0 --port=80"
